# set the lobby using
lobby:
  # Whether the player should be teleported to spawn on join or not
  teleport-spawn: true
  gamemode: ADVENTURE
  fly-enabled: true

match:
  start-countdown: 10.0 # in seconds
  # these settings will be the same for when a participant is eliminated from the game
  end:
    gamemode: SPECTATOR
    fly-enabled: true

queue:
  # how long to wait for more players once a game's minimum player count is met, before starting anyway
  start-countdown: 20.0 # in seconds

version: 2